#!/bin/bash

# Hook file that automatically runs unit tests before a push

CHANGED=$(git diff --name-only HEAD^ HEAD)
make
cd ~
for item in $CHANGED
do
    if [[ $item =~ pyross/stochastic ]];
        then 
            echo "pyross/stochastic changed, running tests..."
            python -m unittest pyross.test.StochasticTest
    elif [[ $item =~ pyross/deterministic ]];
        then
            echo "pyross/deterministic changed, running tests..."
            python -m unittest pyross.test.DeterministicTest
    elif [[ $item =~ pyross/test ]];
        then
            echo "pyross/test changed, running tests..."
            python -m unittest -v pyross.test
    elif [[ $item =~ pyross/control ]];
        then
            echo "pyross/control changed, running tests..."
            python -m unittest pyross.test.ControlTest
    elif [[ $item =~ pyross/inference ]];
        then
            echo "pyross/inference changed, running tests..."
            python -m unittest pyross.test.InferenceTest
    elif [[ $item =~ pyross/forecast ]];
        then
            echo "pyross/forecast changed, running tests..."
            python -m unittest pyross.test.ForecastTest
    
    fi
done;
